//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFileItDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERRALTRANSACTION
    {
        public int ID { get; set; }
        public int REFERRALID { get; set; }
        public Nullable<int> SHAREKEYID { get; set; }
        public Nullable<decimal> COMMISSIONAMOUNT { get; set; }
        public string COMMISSIONPAID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
    
        public virtual SHAREKEY SHAREKEY { get; set; }
        public virtual REFERRAL REFERRAL { get; set; }
    }
}
